/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package phonebook;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author dimps
 */
public class MainDim extends javax.swing.JFrame implements CRUD_Interface{
    public DefaultListModel model = new DefaultListModel<>();
    /**
     * Creates new form MainDim
     */
    public MainDim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEntryDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AddressInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        AddEntryBackButton = new javax.swing.JButton();
        BirthMonthInput = new javax.swing.JTextField();
        BirthYearInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LastNameInput = new javax.swing.JTextField();
        FirstNameInput = new javax.swing.JTextField();
        BirthDayInput = new javax.swing.JTextField();
        NumberInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        UpdateEntryDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        BirthDayTextField = new javax.swing.JTextField();
        BirthMonthTextField = new javax.swing.JTextField();
        NumberTextField = new javax.swing.JTextField();
        BirthYearTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        SearchDialog = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>(model);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LastNameOutput = new javax.swing.JLabel();
        FirstNameOutput = new javax.swing.JLabel();
        BirthdayOutput = new javax.swing.JLabel();
        NumberOutput = new javax.swing.JLabel();
        AddressOutput = new javax.swing.JLabel();
        EmailOutput = new javax.swing.JLabel();
        AddEntry = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        UpdateEntry = new javax.swing.JButton();
        DeleteEntry = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        AddEntryDialog.setMinimumSize(new java.awt.Dimension(499, 400));
        AddEntryDialog.setPreferredSize(new java.awt.Dimension(499, 400));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name:");

        AddressInput.setBackground(new java.awt.Color(204, 255, 255));
        AddressInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Name:");

        SubmitButton.setBackground(new java.awt.Color(0, 102, 0));
        SubmitButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Submit");
        SubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Add New Entry");

        AddEntryBackButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        AddEntryBackButton.setText("Back");
        AddEntryBackButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddEntryBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryBackButtonActionPerformed(evt);
            }
        });

        BirthMonthInput.setBackground(new java.awt.Color(204, 255, 255));
        BirthMonthInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        BirthMonthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthInputActionPerformed(evt);
            }
        });
        BirthMonthInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthMonthInput,2);
            }
        });

        BirthYearInput.setBackground(new java.awt.Color(204, 255, 255));
        BirthYearInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        BirthYearInput.setToolTipText("");
        BirthYearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthYearInputActionPerformed(evt);
            }
        });
        BirthYearInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthYearInput,4);
            }
        });

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Birthday:");

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Number:");

        jLabel11.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address:");

        jLabel12.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email:");

        LastNameInput.setBackground(new java.awt.Color(204, 255, 255));
        LastNameInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        LastNameInput.setToolTipText("");
        LastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameInputActionPerformed(evt);
            }
        });

        FirstNameInput.setBackground(new java.awt.Color(204, 255, 255));
        FirstNameInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N

        BirthDayInput.setBackground(new java.awt.Color(204, 255, 255));
        BirthDayInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        BirthDayInput.setToolTipText("");
        BirthDayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayInputActionPerformed(evt);
            }
        });
        BirthDayInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthDayInput,2);
            }
        });

        NumberInput.setBackground(new java.awt.Color(204, 255, 255));
        NumberInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N

        EmailInput.setBackground(new java.awt.Color(204, 255, 255));
        EmailInput.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("YY");

        jLabel30.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("DD");

        jLabel31.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("MM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(AddEntryBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                                        .addComponent(SubmitButton))
                                    .addComponent(AddressInput)
                                    .addComponent(NumberInput)
                                    .addComponent(EmailInput)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(BirthDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BirthMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(BirthYearInput, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                .addGap(1, 1, 1)))))))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(19, 19, 19)
                                .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BirthDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(AddEntryBackButton))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        SubmitButton.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                String fullDate = BirthDayInput.getText()+"/"+BirthMonthInput.getText()+"/"+BirthYearInput.getText();
                if (FirstNameInput.getText().isEmpty()||LastNameInput.getText().isEmpty()||BirthDayInput.getText().isEmpty()||AddressInput.getText().isEmpty()||EmailInput.getText().isEmpty()||NumberInput.getText().isEmpty()){

                    System.out.println("Error: Incomplete/Improper Data");
                    JOptionPane.showMessageDialog(AddEntryDialog,"Error: Incomplete/Improper","Error",JOptionPane.ERROR_MESSAGE);
                } else{
                    CRUD_Interface.addRow(FirstNameInput.getText(), LastNameInput.getText(), fullDate, AddressInput.getText(), EmailInput.getText(), NumberInput.getText());
                    int index = (model.isEmpty())? 0:indexLocate(model,convertToTitleCaseIteratingChars(FirstNameInput.getText()));
                    model.add(index, FirstNameInput.getText());
                    System.out.println(indexLocate(model,convertToTitleCaseIteratingChars(FirstNameInput.getText())));
                    AddEntryDialog.dispose();
                }
            }
        });
        NumberInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,NumberInput,11);
            }
        });

        javax.swing.GroupLayout AddEntryDialogLayout = new javax.swing.GroupLayout(AddEntryDialog.getContentPane());
        AddEntryDialog.getContentPane().setLayout(AddEntryDialogLayout);
        AddEntryDialogLayout.setHorizontalGroup(
            AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AddEntryDialogLayout.setVerticalGroup(
            AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        UpdateEntryDialog.setMinimumSize(new java.awt.Dimension(499, 400));
        UpdateEntryDialog.setPreferredSize(new java.awt.Dimension(499, 400));
        UpdateEntryDialog.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel19.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Update Entry");

        LastNameTextField.setBackground(new java.awt.Color(204, 255, 255));
        LastNameTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Number:");

        FirstNameTextField.setBackground(new java.awt.Color(204, 255, 255));
        FirstNameTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        BirthDayTextField.setBackground(new java.awt.Color(204, 255, 255));
        BirthDayTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        BirthDayTextField.setName(""); // NOI18N
        BirthDayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayTextFieldActionPerformed(evt);
            }
        });
        BirthDayTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthDayTextField,2);
            }
        });

        BirthMonthTextField.setBackground(new java.awt.Color(204, 255, 255));
        BirthMonthTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        BirthMonthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthTextFieldActionPerformed(evt);
            }
        });

        NumberTextField.setBackground(new java.awt.Color(204, 255, 255));
        NumberTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        NumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTextFieldActionPerformed(evt);
            }
        });

        BirthYearTextField.setBackground(new java.awt.Color(204, 255, 255));
        BirthYearTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N

        EmailTextField.setBackground(new java.awt.Color(204, 255, 255));
        EmailTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Email:");

        jLabel16.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("First Name:");

        AddressTextField.setBackground(new java.awt.Color(204, 255, 255));
        AddressTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        AddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Last Name:");

        UpdateButton.setBackground(new java.awt.Color(0, 102, 0));
        UpdateButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        UpdateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address:");

        jLabel18.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Birthday:");

        jLabel32.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("MM");

        jLabel33.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("YY");

        jLabel34.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("DD");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumberTextField)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(BirthDayTextField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(70, 70, 70)
                                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(BirthMonthTextField)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BirthYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(AddressTextField)
                            .addComponent(EmailTextField)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(FirstNameTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(LastNameTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(BirthDayTextField)
                    .addComponent(BirthMonthTextField)
                    .addComponent(BirthYearTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberTextField)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AddressTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTextField)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(jButton3))
                .addGap(33, 33, 33))
        );

        BirthMonthTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthMonthTextField,2);
            }
        });
        NumberTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,NumberTextField,11);
            }
        });
        BirthYearTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthYearTextField,4);
            }
        });

        javax.swing.GroupLayout UpdateEntryDialogLayout = new javax.swing.GroupLayout(UpdateEntryDialog.getContentPane());
        UpdateEntryDialog.getContentPane().setLayout(UpdateEntryDialogLayout);
        UpdateEntryDialogLayout.setHorizontalGroup(
            UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        UpdateEntryDialogLayout.setVerticalGroup(
            UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout SearchDialogLayout = new javax.swing.GroupLayout(SearchDialog.getContentPane());
        SearchDialog.getContentPane().setLayout(SearchDialogLayout);
        SearchDialogLayout.setHorizontalGroup(
            SearchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SearchDialogLayout.setVerticalGroup(
            SearchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel28.setText("jLabel28");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(450, 300));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        for (int i =0; i<CRUD_Interface.firstNameList.size();i++){
            model.addElement(CRUD_Interface.bubbleSort(CRUD_Interface.firstNameList)[i]);
        }
        jList1.setBackground(new java.awt.Color(204, 255, 255));
        jList1.setModel(model);
        jList1.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent listSelectionEvent){
                boolean adjust = listSelectionEvent.getValueIsAdjusting();
                System.out.println(", Adjusting? " + adjust);
                if (!adjust) {
                    JList list = (JList) listSelectionEvent.getSource();
                    int selections[] = list.getSelectedIndices();
                    Object selectionValues[] = list.getSelectedValues();
                    for (int i = 0, n = selections.length; i < n; i++) {
                        if (i == 0) {
                            System.out.println(" Selections: ");
                        }
                        System.out.println(selections[i] + "/" + selectionValues[i] + " ");
                        String[] Entry = CRUD_Interface.searchRow(selectionValues[i].toString(),CRUD_Interface.firstNameList);
                        LastNameOutput.setText(Entry[1]);
                        FirstNameOutput.setText(Entry[0]);
                        BirthdayOutput.setText(Entry[2]);
                        AddressOutput.setText(Entry[3]);
                        EmailOutput.setText(Entry[4]);
                        NumberOutput.setText(Entry[5]);
                    }
                }

            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setText("Last Name:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Birthday:");

        jLabel4.setText("Number:");

        jLabel5.setText("Address:");

        jLabel6.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNameOutput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FirstNameOutput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BirthdayOutput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailOutput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressOutput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumberOutput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LastNameOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FirstNameOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BirthdayOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumberOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AddressOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EmailOutput))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        AddEntry.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        AddEntry.setText("Add New Entry");
        AddEntry.setToolTipText("");
        AddEntry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryActionPerformed(evt);
            }
        });

        SearchButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Phonebook List");

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("PHONEBOOK APP");

        UpdateEntry.setBackground(new java.awt.Color(0, 153, 0));
        UpdateEntry.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        UpdateEntry.setForeground(new java.awt.Color(255, 255, 255));
        UpdateEntry.setText("Update");
        UpdateEntry.setToolTipText("");
        UpdateEntry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UpdateEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEntryActionPerformed(evt);
            }
        });

        DeleteEntry.setBackground(new java.awt.Color(204, 0, 51));
        DeleteEntry.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        DeleteEntry.setForeground(new java.awt.Color(255, 255, 255));
        DeleteEntry.setText("Delete");
        DeleteEntry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DeleteEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEntryActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Users Info");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(201, 201, 201))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel25))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AddEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(UpdateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddEntry)
                .addGap(128, 128, 128))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void keyStrokeValidate(KeyEvent ke,JTextField InputComponent, int CharCount){
        String field = InputComponent.getText();
        if ((( ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9')&& field.length()  <= CharCount-1)
            ||(ke.getKeyChar() == '-')
            || ke.getKeyCode() == KeyEvent.VK_BACK_SPACE
            || ke.getKeyCode() == KeyEvent.VK_DELETE
            ){
            InputComponent.setEditable(true);
        } else{
            InputComponent.setEditable(false);
        }
    }
    private static boolean InputVerifier(String date,String Email,String number) {
        if (date.matches("^[0-9/]*$")&&Email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")&&number.matches("^[0-9.-]*$")){
            System.out.println("Data Passes Regex Verification");
            return true;     
        } else{
            System.out.println("Data Did not Pass Regex Verification");
            return false;
        }
    }
    public static int indexLocate(DefaultListModel<String> model, String input){
            int i;
            for (i=0;i<model.size();i++){
                //for (int j = i+1;j<model.size();j++){
                    if(model.get(i).compareTo(input) > 0){
                        //System.out.println("<0 " + model.get(i).compareTo(input));
                        break;

                    }
                //}
            }
            return i;
        }
    public static String convertToTitleCaseIteratingChars(String text) {
    if (text == null || text.isEmpty()) {
        return text;
    }

    StringBuilder converted = new StringBuilder();

    boolean convertNext = true;
    for (char ch : text.toCharArray()) {
        if (Character.isSpaceChar(ch)) {
            convertNext = true;
        } else if (convertNext) {
            ch = Character.toTitleCase(ch);
            convertNext = false;
        } else {
            ch = Character.toLowerCase(ch);
        }
        converted.append(ch);
    }

    return converted.toString();
    }
    private void AddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryActionPerformed
        AddEntryDialog.setVisible(true);  
        
    }//GEN-LAST:event_AddEntryActionPerformed
    

    private void UpdateEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEntryActionPerformed
        if(FirstNameOutput.getText().isEmpty()
            ||LastNameOutput.getText().isEmpty()
            ||AddressOutput.getText().isEmpty()
            ||BirthdayOutput.getText().isEmpty()
            || EmailOutput.getText().isEmpty()
            ||NumberOutput.getText().isEmpty()){
            
            System.out.println("Error: No Info to Update");
            JOptionPane.showMessageDialog(rootPane,"Error: No Info to Update","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            UpdateEntryDialog.setVisible(true);
            FirstNameTextField.setText(FirstNameOutput.getText());
            LastNameTextField.setText(LastNameOutput.getText());
            AddressTextField.setText(AddressOutput.getText());
            String[] DateSplices = BirthdayOutput.getText().split("/");
            BirthDayTextField.setText(DateSplices[0]);
            BirthMonthTextField.setText(DateSplices[1]);
            BirthYearTextField.setText(DateSplices[2]);
            EmailTextField.setText(EmailOutput.getText());
            NumberTextField.setText(NumberOutput.getText());
        }
        
        
    }//GEN-LAST:event_UpdateEntryActionPerformed
    private static void DeleteGUIChoice(DefaultListModel<String> model, String input ){
        try{
            int i;
            for (i=0;i<model.size();i++){
                    if(model.get(i).equals(input)){
                        model.remove(i);
                        System.out.println("GUI block removed");
                        break;
                    }
            }
        }catch(Exception err){
            System.out.println(err);
        }
        
    }
    private void DeleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEntryActionPerformed
        // TODO add your handling code here:
        if(FirstNameOutput.getText().isEmpty()
            ||LastNameOutput.getText().isEmpty()
            ||AddressOutput.getText().isEmpty()
            ||BirthdayOutput.getText().isEmpty()
            || EmailOutput.getText().isEmpty()
            ||NumberOutput.getText().isEmpty()){
            
            System.out.println("Error: No Info to Delete");
            JOptionPane.showMessageDialog(rootPane,"Error: No Info to Delete","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String[] choices= {"Yes","No"};
            int response=JOptionPane.showOptionDialog(this, "Do you confirm the Deletion of These Data?", "Deletion Confirmation", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, choices, choices[0]);
            switch (response) {
                case 0 -> {
                    CRUD_Interface.deleteRow(FirstNameOutput.getText(), EmailOutput.getText());
                    DeleteGUIChoice(model,FirstNameOutput.getText());
                    System.out.println("Data Deleted");
                    FirstNameOutput.setText("");
                    LastNameOutput.setText("");
                    AddressOutput.setText("");
                    BirthdayOutput.setText("");
                    EmailOutput.setText("");
                    NumberOutput.setText("");
                    CRUD_Interface.getAllRows();
                }
                case 1 -> System.out.println("Deletion cancelled");
                default -> System.out.println("No Choice");
            }
        }
    }//GEN-LAST:event_DeleteEntryActionPerformed

    private void BirthDayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDayInputActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void BirthDayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BirthDayTextFieldActionPerformed

    private void NumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void AddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String NewBirthDate = BirthDayTextField.getText()+"/"+BirthMonthTextField.getText()+"/"+BirthYearTextField.getText();
        if(InputVerifier(NewBirthDate, EmailTextField.getText(),NumberTextField.getText())){
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.firstNameList, FirstNameTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.lastNameList, LastNameTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.BirthdayList, NewBirthDate);
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.numberList, NumberTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.AddressList, AddressTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.EmailList, EmailTextField.getText());
            model.removeElement(FirstNameOutput.getText());
            model.add(indexLocate(model,   convertToTitleCaseIteratingChars(FirstNameTextField.getText())),FirstNameTextField.getText());
            FirstNameOutput.setText(FirstNameTextField.getText());
            LastNameOutput.setText(LastNameTextField.getText());
            BirthdayOutput.setText(NewBirthDate);
            NumberOutput.setText(NumberTextField.getText());
            AddressOutput.setText(AddressTextField.getText());
            EmailOutput.setText(EmailTextField.getText());
            UpdateEntryDialog.dispose();
            CRUD_Interface.getAllRows();
        }else{
            JOptionPane.showMessageDialog( UpdateEntryDialog,"Error: Incorrect Data","Error",JOptionPane.ERROR_MESSAGE);
            AddEntryDialog.dispose();
        }
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        UpdateEntryDialog.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddEntryBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryBackButtonActionPerformed
        // TODO add your handling code here:
        AddEntryDialog.dispose();
    }//GEN-LAST:event_AddEntryBackButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        CRUD_Interface.getAllRows();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BirthMonthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthInputActionPerformed

    private void BirthYearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthYearInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthYearInputActionPerformed

    private void BirthMonthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthTextFieldActionPerformed

    private void LastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameInputActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try{
            String query = JOptionPane.showInputDialog(rootPane, "Input query here (case-sensitive):");  
            if (CRUD_Interface.SearchAllFields(query)!= null){
                String[] findings = CRUD_Interface.SearchAllFields(query);
                FirstNameOutput.setText(findings[0]);
                LastNameOutput.setText(findings[1]);
                BirthdayOutput.setText(findings[2]);
                AddressOutput.setText(findings[3]);
                EmailOutput.setText(findings[4]);
                NumberOutput.setText(findings[5]);
                System.out.println("Found");
                jList1.setCellRenderer(new DefaultListCellRenderer(){
                    @Override
                    public Component getListCellRendererComponent(JList list, Object value,int index, boolean isSelected, boolean cellHasFocus) {
                        super.getListCellRendererComponent(list, value, index, isSelected,cellHasFocus);
                        String num = (String) value;
                        if (num.equals(findings[0])) {
                          setBackground(Color.lightGray);
                        }
                        return this;
                    }                
                });
            }
        }catch(ArrayIndexOutOfBoundsException err){
            JOptionPane.showMessageDialog(rootPane,"Error: Query Not Found","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println("not Found");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEntry;
    private javax.swing.JButton AddEntryBackButton;
    private javax.swing.JDialog AddEntryDialog;
    private javax.swing.JTextField AddressInput;
    private javax.swing.JLabel AddressOutput;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField BirthDayInput;
    private javax.swing.JTextField BirthDayTextField;
    private javax.swing.JTextField BirthMonthInput;
    private javax.swing.JTextField BirthMonthTextField;
    private javax.swing.JTextField BirthYearInput;
    private javax.swing.JTextField BirthYearTextField;
    private javax.swing.JLabel BirthdayOutput;
    private javax.swing.JButton DeleteEntry;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailOutput;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstNameInput;
    private javax.swing.JLabel FirstNameOutput;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameInput;
    private javax.swing.JLabel LastNameOutput;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField NumberInput;
    private javax.swing.JLabel NumberOutput;
    private javax.swing.JTextField NumberTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JDialog SearchDialog;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton UpdateEntry;
    private javax.swing.JDialog UpdateEntryDialog;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
